version: '3.8'
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
    - "3000:3000"
    networks:
    - app-network
    depends_on:
    - redis

  db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
    networks:
    - app-network
    depends_on:
    - backend
    volumes:
     - db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
    - app-network
  redis:
    image: redis
    restart: always
    volumes:
    - redis-data:/data
    ports:
      - 6379:6379
    
    networks:
    - app-network
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=redis
      - HTTP_USER=default
      - HTTP_PASSWORD=password
    ports:
      - 8081:8081
    networks:
      - app-network
    depends_on:
      - redis
  
  
volumes:
  db-data:
  redis-data:
  


networks:
  app-network:
    driver: bridge